stages:
    - test

postman_tests:
    stage: test
    image: 
        name: postman/newman_alpine33
        entrypoint: [""]
    script: 
        - newman --version
        - npm install -g newman-reporter-html
        - newman run APIAutomation.postman_collection.json -e NMEnvironment.postman_environment.json --reporters cli,html --reporter-html-export report.html
    
    artifacts:
        when: always
        paths:
           - report.html
    
    environment:
        name: testing
        url: https://gitlab.com/leutermanns/testing
